// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: gochat.proto

package gochat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*C2SMessage_ChatMessage_
	//	*C2SMessage_Ident_
	Content isC2SMessage_Content `protobuf_oneof:"content"`
}

func (x *C2SMessage) Reset() {
	*x = C2SMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMessage) ProtoMessage() {}

func (x *C2SMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMessage.ProtoReflect.Descriptor instead.
func (*C2SMessage) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{0}
}

func (m *C2SMessage) GetContent() isC2SMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *C2SMessage) GetChatMessage() *C2SMessage_ChatMessage {
	if x, ok := x.GetContent().(*C2SMessage_ChatMessage_); ok {
		return x.ChatMessage
	}
	return nil
}

func (x *C2SMessage) GetIdent() *C2SMessage_Ident {
	if x, ok := x.GetContent().(*C2SMessage_Ident_); ok {
		return x.Ident
	}
	return nil
}

type isC2SMessage_Content interface {
	isC2SMessage_Content()
}

type C2SMessage_ChatMessage_ struct {
	ChatMessage *C2SMessage_ChatMessage `protobuf:"bytes,2,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type C2SMessage_Ident_ struct {
	Ident *C2SMessage_Ident `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

func (*C2SMessage_ChatMessage_) isC2SMessage_Content() {}

func (*C2SMessage_Ident_) isC2SMessage_Content() {}

type S2CMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*S2CMessage_ChatMessage_
	//	*S2CMessage_Join_
	//	*S2CMessage_Part_
	//	*S2CMessage_NickChange_
	Content isS2CMessage_Content `protobuf_oneof:"content"`
}

func (x *S2CMessage) Reset() {
	*x = S2CMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage) ProtoMessage() {}

func (x *S2CMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage.ProtoReflect.Descriptor instead.
func (*S2CMessage) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1}
}

func (m *S2CMessage) GetContent() isS2CMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *S2CMessage) GetChatMessage() *S2CMessage_ChatMessage {
	if x, ok := x.GetContent().(*S2CMessage_ChatMessage_); ok {
		return x.ChatMessage
	}
	return nil
}

func (x *S2CMessage) GetJoin() *S2CMessage_Join {
	if x, ok := x.GetContent().(*S2CMessage_Join_); ok {
		return x.Join
	}
	return nil
}

func (x *S2CMessage) GetPart() *S2CMessage_Part {
	if x, ok := x.GetContent().(*S2CMessage_Part_); ok {
		return x.Part
	}
	return nil
}

func (x *S2CMessage) GetNickChange() *S2CMessage_NickChange {
	if x, ok := x.GetContent().(*S2CMessage_NickChange_); ok {
		return x.NickChange
	}
	return nil
}

type isS2CMessage_Content interface {
	isS2CMessage_Content()
}

type S2CMessage_ChatMessage_ struct {
	ChatMessage *S2CMessage_ChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type S2CMessage_Join_ struct {
	Join *S2CMessage_Join `protobuf:"bytes,2,opt,name=join,proto3,oneof"`
}

type S2CMessage_Part_ struct {
	Part *S2CMessage_Part `protobuf:"bytes,3,opt,name=part,proto3,oneof"`
}

type S2CMessage_NickChange_ struct {
	NickChange *S2CMessage_NickChange `protobuf:"bytes,4,opt,name=nick_change,json=nickChange,proto3,oneof"`
}

func (*S2CMessage_ChatMessage_) isS2CMessage_Content() {}

func (*S2CMessage_Join_) isS2CMessage_Content() {}

func (*S2CMessage_Part_) isS2CMessage_Content() {}

func (*S2CMessage_NickChange_) isS2CMessage_Content() {}

type C2SMessage_ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel  string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsAction bool   `protobuf:"varint,3,opt,name=is_action,json=isAction,proto3" json:"is_action,omitempty"`
}

func (x *C2SMessage_ChatMessage) Reset() {
	*x = C2SMessage_ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMessage_ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMessage_ChatMessage) ProtoMessage() {}

func (x *C2SMessage_ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMessage_ChatMessage.ProtoReflect.Descriptor instead.
func (*C2SMessage_ChatMessage) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *C2SMessage_ChatMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *C2SMessage_ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *C2SMessage_ChatMessage) GetIsAction() bool {
	if x != nil {
		return x.IsAction
	}
	return false
}

type C2SMessage_Ident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *C2SMessage_Ident) Reset() {
	*x = C2SMessage_Ident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMessage_Ident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMessage_Ident) ProtoMessage() {}

func (x *C2SMessage_Ident) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMessage_Ident.ProtoReflect.Descriptor instead.
func (*C2SMessage_Ident) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{0, 1}
}

func (x *C2SMessage_Ident) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type S2CMessage_ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Channel  string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsAction bool   `protobuf:"varint,4,opt,name=is_action,json=isAction,proto3" json:"is_action,omitempty"`
}

func (x *S2CMessage_ChatMessage) Reset() {
	*x = S2CMessage_ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMessage_ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage_ChatMessage) ProtoMessage() {}

func (x *S2CMessage_ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage_ChatMessage.ProtoReflect.Descriptor instead.
func (*S2CMessage_ChatMessage) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1, 0}
}

func (x *S2CMessage_ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *S2CMessage_ChatMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *S2CMessage_ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *S2CMessage_ChatMessage) GetIsAction() bool {
	if x != nil {
		return x.IsAction
	}
	return false
}

type S2CMessage_Join struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *S2CMessage_Join) Reset() {
	*x = S2CMessage_Join{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMessage_Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage_Join) ProtoMessage() {}

func (x *S2CMessage_Join) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage_Join.ProtoReflect.Descriptor instead.
func (*S2CMessage_Join) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1, 1}
}

func (x *S2CMessage_Join) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type S2CMessage_Part struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *S2CMessage_Part) Reset() {
	*x = S2CMessage_Part{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMessage_Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage_Part) ProtoMessage() {}

func (x *S2CMessage_Part) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage_Part.ProtoReflect.Descriptor instead.
func (*S2CMessage_Part) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1, 2}
}

func (x *S2CMessage_Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type S2CMessage_NickChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *S2CMessage_NickChange) Reset() {
	*x = S2CMessage_NickChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMessage_NickChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage_NickChange) ProtoMessage() {}

func (x *S2CMessage_NickChange) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage_NickChange.ProtoReflect.Descriptor instead.
func (*S2CMessage_NickChange) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1, 3}
}

func (x *S2CMessage_NickChange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *S2CMessage_NickChange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_gochat_proto protoreflect.FileDescriptor

var file_gochat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x62, 0x75, 0x66, 0x22, 0x85, 0x02, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x75, 0x66, 0x2e, 0x43,
	0x32, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x32, 0x53, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x1a, 0x5e, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x0a, 0x05, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xce, 0x03, 0x0a, 0x0a,
	0x53, 0x32, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x32, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04,
	0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x32, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x48, 0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x32, 0x43,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x70, 0x61, 0x72, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x32, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x69, 0x63, 0x6b, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x69, 0x63, 0x6b, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x1a, 0x72, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a,
	0x30, 0x0a, 0x0a, 0x4e, 0x69, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2f,
	0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gochat_proto_rawDescOnce sync.Once
	file_gochat_proto_rawDescData = file_gochat_proto_rawDesc
)

func file_gochat_proto_rawDescGZIP() []byte {
	file_gochat_proto_rawDescOnce.Do(func() {
		file_gochat_proto_rawDescData = protoimpl.X.CompressGZIP(file_gochat_proto_rawDescData)
	})
	return file_gochat_proto_rawDescData
}

var file_gochat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gochat_proto_goTypes = []interface{}{
	(*C2SMessage)(nil),             // 0: buf.C2SMessage
	(*S2CMessage)(nil),             // 1: buf.S2CMessage
	(*C2SMessage_ChatMessage)(nil), // 2: buf.C2SMessage.ChatMessage
	(*C2SMessage_Ident)(nil),       // 3: buf.C2SMessage.Ident
	(*S2CMessage_ChatMessage)(nil), // 4: buf.S2CMessage.ChatMessage
	(*S2CMessage_Join)(nil),        // 5: buf.S2CMessage.Join
	(*S2CMessage_Part)(nil),        // 6: buf.S2CMessage.Part
	(*S2CMessage_NickChange)(nil),  // 7: buf.S2CMessage.NickChange
}
var file_gochat_proto_depIdxs = []int32{
	2, // 0: buf.C2SMessage.chat_message:type_name -> buf.C2SMessage.ChatMessage
	3, // 1: buf.C2SMessage.ident:type_name -> buf.C2SMessage.Ident
	4, // 2: buf.S2CMessage.chat_message:type_name -> buf.S2CMessage.ChatMessage
	5, // 3: buf.S2CMessage.join:type_name -> buf.S2CMessage.Join
	6, // 4: buf.S2CMessage.part:type_name -> buf.S2CMessage.Part
	7, // 5: buf.S2CMessage.nick_change:type_name -> buf.S2CMessage.NickChange
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gochat_proto_init() }
func file_gochat_proto_init() {
	if File_gochat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gochat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMessage_ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMessage_Ident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMessage_ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMessage_Join); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMessage_Part); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMessage_NickChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gochat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*C2SMessage_ChatMessage_)(nil),
		(*C2SMessage_Ident_)(nil),
	}
	file_gochat_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*S2CMessage_ChatMessage_)(nil),
		(*S2CMessage_Join_)(nil),
		(*S2CMessage_Part_)(nil),
		(*S2CMessage_NickChange_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gochat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gochat_proto_goTypes,
		DependencyIndexes: file_gochat_proto_depIdxs,
		MessageInfos:      file_gochat_proto_msgTypes,
	}.Build()
	File_gochat_proto = out.File
	file_gochat_proto_rawDesc = nil
	file_gochat_proto_goTypes = nil
	file_gochat_proto_depIdxs = nil
}
